### PR TITLE
chore: migrate from yarnv1 to pnpm

### PR DESCRIPTION
**Pull request by marcustyphoon**
Working package manager migration from yarn classic to PNPM@8.

### CODE REVIEW

**Comment by gw2princeps** [comment]
Pretty cool, about time we get rid of yarn entirely!

**Comment by marcustyphoon** [comment]
So, the only note I should add this is that I don't know from personal experience the details of how deployment works when you have `"workspace:^"` dependencies.

My understanding of https://pnpm.io/workspaces#publishing-workspace-packages is what I would expect, i.e. if you make changes to gw2-ui, version bump it, make changes to react-discretize-components, version bump that, and deploy, the new version of react-discretize-components depends on the new version of gw2-ui. This is what you would do manually.

However, if you make changes to gw2-ui, version bump it, make **completely unrelated** changes to react-discretize-components, version bump that, and deploy, the new version of react-discretize-components **still** depends on the new version of gw2-ui. You might not have done that manually. Seems harmless though.

**Comment by gw2princeps** [comment]
Looks good to me! Shall we merge?

**Comment by marcustyphoon** [comment]
I was debating if we have to coordinate with anyone else on something like this, but I guess it's not like there are lots of people working on this on a weekly basis or whatever who would be surprised by it (and it's not like it's a lot of steps to `npx npkill`, install pnpm, and `pnpm i`). Should probably be fine I think?

**Comment by gw2princeps** [comment]
You and me are the only ones who commit code. Everyone else will figure it out :)

**Pull request merged**
